//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTestingBL.AuthenticationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.IAuthenticationService")]
    public interface IAuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/GetTokenAccessForMobileUser", ReplyAction="http://tempuri.org/IAuthenticationService/GetTokenAccessForMobileUserResponse")]
        System.Guid GetTokenAccessForMobileUser(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/GetTokenAccessForMobileUser", ReplyAction="http://tempuri.org/IAuthenticationService/GetTokenAccessForMobileUserResponse")]
        System.Threading.Tasks.Task<System.Guid> GetTokenAccessForMobileUserAsync(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/AuthenticateWebSiteUser", ReplyAction="http://tempuri.org/IAuthenticationService/AuthenticateWebSiteUserResponse")]
        bool AuthenticateWebSiteUser(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/AuthenticateWebSiteUser", ReplyAction="http://tempuri.org/IAuthenticationService/AuthenticateWebSiteUserResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateWebSiteUserAsync(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/RegisterNewUser", ReplyAction="http://tempuri.org/IAuthenticationService/RegisterNewUserResponse")]
        bool RegisterNewUser(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/RegisterNewUser", ReplyAction="http://tempuri.org/IAuthenticationService/RegisterNewUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterNewUserAsync(string email, string passwordHash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticationServiceChannel : ServiceTestingBL.AuthenticationService.IAuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<ServiceTestingBL.AuthenticationService.IAuthenticationService>, ServiceTestingBL.AuthenticationService.IAuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid GetTokenAccessForMobileUser(string email, string passwordHash) {
            return base.Channel.GetTokenAccessForMobileUser(email, passwordHash);
        }
        
        public System.Threading.Tasks.Task<System.Guid> GetTokenAccessForMobileUserAsync(string email, string passwordHash) {
            return base.Channel.GetTokenAccessForMobileUserAsync(email, passwordHash);
        }
        
        public bool AuthenticateWebSiteUser(string email, string passwordHash) {
            return base.Channel.AuthenticateWebSiteUser(email, passwordHash);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateWebSiteUserAsync(string email, string passwordHash) {
            return base.Channel.AuthenticateWebSiteUserAsync(email, passwordHash);
        }
        
        public bool RegisterNewUser(string email, string passwordHash) {
            return base.Channel.RegisterNewUser(email, passwordHash);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterNewUserAsync(string email, string passwordHash) {
            return base.Channel.RegisterNewUserAsync(email, passwordHash);
        }
    }
}
